// Telegrammer - Telegram TGBot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/**
 A placeholder, currently holds no information. Use TGBotFather to set up your game.

 SeeAlso Telegram TGBot API Reference:
 [CallbackGame](https://core.telegram.org/bots/api#callbackgame)
 */
public final class CallbackGame: Codable {

}
