// Telegrammer - Telegram TGBot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/**
 This object represents an error in the Telegram Passport element which was submitted that should be resolved by the user. It should be one of:
 PassportElementErrorDataField
 PassportElementErrorFrontSide
 PassportElementErrorReverseSide
 PassportElementErrorSelfie
 PassportElementErrorFile
 PassportElementErrorFiles
 
 SeeAlso Telegram TGBot API Reference:
 [PassportElementError](https://core.telegram.org/bots/api#passportelementerror)
 */
public enum TGPassportElementError: Codable {
    case dataField(TGPassportElementErrorDataField)
    case file(TGPassportElementErrorFile)
    case files(TGPassportElementErrorFiles)
    case frontSide(TGPassportElementErrorFrontSide)
    case reverseSide(TGPassportElementErrorReverseSide)
    case selfie(TGPassportElementErrorSelfie)
    case unknown

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .dataField(let value):
            try container.encode(value)
        case .file(let value):
            try container.encode(value)
        case .files(let value):
            try container.encode(value)
        case .frontSide(let value):
            try container.encode(value)
        case .reverseSide(let value):
            try container.encode(value)
        case .selfie(let value):
            try container.encode(value)
        case .unknown:
            try container.encodeNil()
        }
    }

    public init(from decoder: Decoder) throws {
        if let value = try? decoder.singleValueContainer().decode(TGPassportElementErrorDataField.self) {
            self = .dataField(value)
            return
        }
        if let value = try? decoder.singleValueContainer().decode(TGPassportElementErrorFile.self) {
            self = .file(value)
            return
        }
        if let value = try? decoder.singleValueContainer().decode(TGPassportElementErrorFiles.self) {
            self = .files(value)
            return
        }
        if let value = try? decoder.singleValueContainer().decode(TGPassportElementErrorFrontSide.self) {
            self = .frontSide(value)
            return
        }
        if let value = try? decoder.singleValueContainer().decode(TGPassportElementErrorReverseSide.self) {
            self = .reverseSide(value)
            return
        }
        if let value = try? decoder.singleValueContainer().decode(TGPassportElementErrorSelfie.self) {
            self = .selfie(value)
            return
        }
        self = .unknown
    }

}
