// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.
import Vapor

public extension TGBot {

    /**
     Use this method to remove webhook integration if you decide to switch back to getUpdates. Returns True on success. Requires no parameters.

     SeeAlso Telegram Bot API Reference:
     [DeleteWebhookParams](https://core.telegram.org/bots/api#deletewebhook)
     
     - Parameters:
         - params: Parameters container, see `DeleteWebhookParams` struct
     - Throws: Throws on errors
     - Returns: Future of `Bool` type
     */

    @discardableResult
    func deleteWebhook() throws -> EventLoopFuture<Bool> {
        let methodURL: URI = .init(string: getMethodURL("deleteWebhook"))
        let future: EventLoopFuture<Bool> = tgClient.post(methodURL)
        return future
    }
}
