// Telegram-vapor-bot - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

import Vapor

/// DESCRIPTION:
/// Use this method to edit a non-primary invite link created by the bot. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns the edited invite link as a ChatInviteLink object.


/// Parameters container struct for `editChatInviteLink` method
public struct TGEditChatInviteLinkParams: Encodable {

    /// Unique identifier for the target chat or username of the target channel (in the format @channelusername)
    public var chatId: TGChatId

    /// The invite link to edit
    public var inviteLink: String

    /// Point in time (Unix timestamp) when the link will expire
    public var expireDate: Int?

    /// Maximum number of users that can be members of the chat simultaneously after joining the chat via this invite link; 1-99999
    public var memberLimit: Int?

    /// Custom keys for coding/decoding `EditChatInviteLinkParams` struct
    public enum CodingKeys: String, CodingKey {
            case chatId = "chat_id"
            case inviteLink = "invite_link"
            case expireDate = "expire_date"
            case memberLimit = "member_limit"
    }

    public init(chatId: TGChatId, inviteLink: String, expireDate: Int? = nil, memberLimit: Int? = nil) {
            self.chatId = chatId
            self.inviteLink = inviteLink
            self.expireDate = expireDate
            self.memberLimit = memberLimit
    }
}


public extension TGBot {

/**
 Use this method to edit a non-primary invite link created by the bot. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns the edited invite link as a ChatInviteLink object.

 SeeAlso Telegram Bot API Reference:
 [EditChatInviteLinkParams](https://core.telegram.org/bots/api#editchatinvitelink)
 
 - Parameters:
     - params: Parameters container, see `EditChatInviteLinkParams` struct
 - Throws: Throws on errors
 - Returns: EventLoopFuture of `Bool` type
 */
    @discardableResult
    func editChatInviteLink(params: TGEditChatInviteLinkParams) throws -> EventLoopFuture<Bool> {
        let methodURL: URI = .init(string: getMethodURL("editChatInviteLink"))
        let future: EventLoopFuture<Bool> = tgClient.post(methodURL, params: params, as: nil)
        return future
    }
}
