// Telegram-vapor-bot-lib - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

import Vapor

/// DESCRIPTION:
/// Use this method to get the current list of the bot's commands. Requires no parameters. Returns Array of BotCommand on success.



public extension TGBot {

/**
 Use this method to get the current list of the bot's commands. Requires no parameters. Returns Array of BotCommand on success.

 SeeAlso Telegram Bot API Reference:
 [GetMyCommandsParams](https://core.telegram.org/bots/api#getmycommands)
 
 - Parameters:
     - params: Parameters container, see `GetMyCommandsParams` struct
 - Throws: Throws on errors
 - Returns: EventLoopFuture of `[TGBotCommand]` type
 */
    @discardableResult
    func getMyCommands() throws -> EventLoopFuture<[TGBotCommand]> {
        let methodURL: URI = .init(string: getMethodURL("getMyCommands"))
        let future: EventLoopFuture<[TGBotCommand]> = tgClient.post(methodURL)
        return future
    }
}
