// Telegram-vapor-bot - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

import Vapor

/// DESCRIPTION:
/// Use this method to change the list of the bot's commands. Returns True on success.


/// Parameters container struct for `setMyCommands` method
public struct TGSetMyCommandsParams: Encodable {

    /// A JSON-serialized list of bot commands to be set as the list of the bot's commands. At most 100 commands can be specified.
    public var commands: [TGBotCommand]

    /// Custom keys for coding/decoding `SetMyCommandsParams` struct
    public enum CodingKeys: String, CodingKey {
            case commands = "commands"
    }

    public init(commands: [TGBotCommand]) {
            self.commands = commands
    }
}


public extension TGBot {

/**
 Use this method to change the list of the bot's commands. Returns True on success.

 SeeAlso Telegram Bot API Reference:
 [SetMyCommandsParams](https://core.telegram.org/bots/api#setmycommands)
 
 - Parameters:
     - params: Parameters container, see `SetMyCommandsParams` struct
 - Throws: Throws on errors
 - Returns: EventLoopFuture of `Bool` type
 */
    @discardableResult
    func setMyCommands(params: TGSetMyCommandsParams) throws -> EventLoopFuture<Bool> {
        let methodURL: URI = .init(string: getMethodURL("setMyCommands"))
        let future: EventLoopFuture<Bool> = tgClient.post(methodURL, params: params, as: nil)
        return future
    }
}
