// Telegram-vapor-bot - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/**
 This object represents a service message about a video chat started in the chat. Currently holds no information.

 SeeAlso Telegram Bot API Reference:
 [VideoChatStarted](https://core.telegram.org/bots/api#videochatstarted)
 */
public final class TGVideoChatStarted: Codable {

}
