// Telegram-vapor-bot-lib - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/**
 This object represents a service message about new members invited to a voice chat.

 SeeAlso Telegram Bot API Reference:
 [VoiceChatParticipantsInvited](https://core.telegram.org/bots/api#voicechatparticipantsinvited)
 */
public final class TGVoiceChatParticipantsInvited: Codable {

    /// Custom keys for coding/decoding `VoiceChatParticipantsInvited` struct
    public enum CodingKeys: String, CodingKey {
        case users = "users"
    }

    /// Optional. New members that were invited to the voice chat
    public var users: [TGUser]?

    public init (users: [TGUser]? = nil) {
        self.users = users
    }
}
