// Telegram-vapor-bot-lib - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

import Vapor

/// DESCRIPTION:
/// A simple method for testing your bot's auth token. Requires no parameters. Returns basic information about the bot in form of a User object.



public extension TGBot {

/**
 A simple method for testing your bot's auth token. Requires no parameters. Returns basic information about the bot in form of a User object.

 SeeAlso Telegram Bot API Reference:
 [GetMeParams](https://core.telegram.org/bots/api#getme)
 
 - Parameters:
     - params: Parameters container, see `GetMeParams` struct
 - Throws: Throws on errors
 - Returns: EventLoopFuture of `TGUser` type
 */
    @discardableResult
    func getMe() throws -> EventLoopFuture<TGUser> {
        let methodURL: URI = .init(string: getMethodURL("getMe"))
        let future: EventLoopFuture<TGUser> = tgClient.post(methodURL)
        return future
    }
}
