// Telegram-vapor-bot-lib - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

import Vapor

/// DESCRIPTION:
/// Use this method to log out from the cloud Bot API server before launching the bot locally. You must log out the bot before running it locally, otherwise there is no guarantee that the bot will receive updates. After a successful call, you can immediately log in on a local server, but will not be able to log in back to the cloud Bot API server for 10 minutes. Returns True on success. Requires no parameters.



public extension TGBot {

/**
 Use this method to log out from the cloud Bot API server before launching the bot locally. You must log out the bot before running it locally, otherwise there is no guarantee that the bot will receive updates. After a successful call, you can immediately log in on a local server, but will not be able to log in back to the cloud Bot API server for 10 minutes. Returns True on success. Requires no parameters.

 SeeAlso Telegram Bot API Reference:
 [LogOutParams](https://core.telegram.org/bots/api#logout)
 
 - Parameters:
     - params: Parameters container, see `LogOutParams` struct
 - Throws: Throws on errors
 - Returns: EventLoopFuture of `Bool` type
 */
    @discardableResult
    func logOut() throws -> EventLoopFuture<Bool> {
        let methodURL: URI = .init(string: getMethodURL("logOut"))
        let future: EventLoopFuture<Bool> = tgClient.post(methodURL)
        return future
    }
}
