// Telegram-vapor-bot-lib - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

import Vapor

public extension TGBot {

    /**
     Use this method to get the current list of the bot's commands. Requires no parameters. Returns Array of BotCommand on success.

     SeeAlso Telegram Bot API Reference:
     [GetMyCommandsParams](https://core.telegram.org/bots/api#getmycommands)
     
     - Parameters:
         - params: Parameters container, see `GetMyCommandsParams` struct
     - Throws: Throws on errors
     - Returns: EventLoopFuture of `[BotCommand]` type
     */
    @discardableResult
    func getMyCommands() throws -> EventLoopFuture<[BotCommand]> {
        let methodURL: URI = .init(string: getMethodURL("getMyCommands"))
        let future: EventLoopFuture<[BotCommand]> = tgClient.post(methodURL)
        return future
    }
}
