// Telegram-vapor-bot-lib - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

public extension TGBot {

    /// Parameters container struct for `setMyCommands` method
    struct SetMyCommandsParams: Encodable {

        /// A JSON-serialized list of bot commands to be set as the list of the bot's commands. At most 100 commands can be specified.
        var commands: [BotCommand]

        /// Custom keys for coding/decoding `SetMyCommandsParams` struct
        enum CodingKeys: String, CodingKey {
            case commands = "commands"
        }

        public init(commands: [BotCommand]) {
            self.commands = commands
        }
    }

    /**
     Use this method to change the list of the bot's commands. Returns True on success.

     SeeAlso Telegram Bot API Reference:
     [SetMyCommandsParams](https://core.telegram.org/bots/api#setmycommands)
     
     - Parameters:
         - params: Parameters container, see `SetMyCommandsParams` struct
     - Throws: Throws on errors
     - Returns: EventLoopFuture of `Bool` type
     */
    @discardableResult
    func setMyCommands(params: SetMyCommandsParams) throws -> EventLoopFuture<Bool> {
        let methodURL: URI = .init(string: getMethodURL("setMyCommands"))
        let future: EventLoopFuture<Bool> = tgClient.post(methodURL, params: params)
        return future
    }
}
