// Telegram-vapor-bot-lib - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

public extension TGBot {

    /// Parameters container struct for `editChatInviteLink` method
    struct EditChatInviteLinkParams: Encodable {

        /// Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        var chatId: ChatId

        /// The invite link to edit
        var inviteLink: String

        /// Point in time (Unix timestamp) when the link will expire
        var expireDate: Int?

        /// Maximum number of users that can be members of the chat simultaneously after joining the chat via this invite link; 1-99999
        var memberLimit: Int?

        /// Custom keys for coding/decoding `EditChatInviteLinkParams` struct
        enum CodingKeys: String, CodingKey {
            case chatId = "chat_id"
            case inviteLink = "invite_link"
            case expireDate = "expire_date"
            case memberLimit = "member_limit"
        }

        public init(chatId: ChatId, inviteLink: String, expireDate: Int? = nil, memberLimit: Int? = nil) {
            self.chatId = chatId
            self.inviteLink = inviteLink
            self.expireDate = expireDate
            self.memberLimit = memberLimit
        }
    }

    /**
     Use this method to edit a non-primary invite link created by the bot. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns the edited invite link as a ChatInviteLink object.

     SeeAlso Telegram Bot API Reference:
     [EditChatInviteLinkParams](https://core.telegram.org/bots/api#editchatinvitelink)
     
     - Parameters:
         - params: Parameters container, see `EditChatInviteLinkParams` struct
     - Throws: Throws on errors
     - Returns: EventLoopFuture of `Bool` type
     */
    @discardableResult
    func editChatInviteLink(params: EditChatInviteLinkParams) throws -> EventLoopFuture<Bool> {
        let methodURL: URI = .init(string: getMethodURL("editChatInviteLink"))
        let future: EventLoopFuture<Bool> = tgClient.post(methodURL, params: params)
        return future
    }
}
