// Telegram-vapor-bot-lib - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

import Vapor

public extension TGBot {

    /// Parameters container struct for `getStickerSet` method
    struct GetStickerSetParams: Encodable {

        /// Name of the sticker set
        var name: String

        /// Custom keys for coding/decoding `GetStickerSetParams` struct
        enum CodingKeys: String, CodingKey {
            case name = "name"
        }

        public init(name: String) {
            self.name = name
        }
    }

    /**
     Use this method to get a sticker set. On success, a StickerSet object is returned.

     SeeAlso Telegram Bot API Reference:
     [GetStickerSetParams](https://core.telegram.org/bots/api#getstickerset)
     
     - Parameters:
         - params: Parameters container, see `GetStickerSetParams` struct
     - Throws: Throws on errors
     - Returns: EventLoopFuture of `StickerSet` type
     */
    @discardableResult
    func getStickerSet(params: GetStickerSetParams) throws -> EventLoopFuture<StickerSet> {
        let methodURL: URI = .init(string: getMethodURL("getStickerSet"))
        let future: EventLoopFuture<StickerSet> = tgClient.post(methodURL, params: params)
        return future
    }
}
