// Telegram-vapor-bot-lib - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

import Vapor

public extension TGBot {

    /// Parameters container struct for `setChatDescription` method
    struct SetChatDescriptionParams: Encodable {

        /// Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        var chatId: ChatId

        /// New chat description, 0-255 characters
        var description: String?

        /// Custom keys for coding/decoding `SetChatDescriptionParams` struct
        enum CodingKeys: String, CodingKey {
            case chatId = "chat_id"
            case description = "description"
        }

        public init(chatId: ChatId, description: String? = nil) {
            self.chatId = chatId
            self.description = description
        }
    }

    /**
     Use this method to change the description of a group, a supergroup or a channel. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns True on success.

     SeeAlso Telegram Bot API Reference:
     [SetChatDescriptionParams](https://core.telegram.org/bots/api#setchatdescription)
     
     - Parameters:
         - params: Parameters container, see `SetChatDescriptionParams` struct
     - Throws: Throws on errors
     - Returns: EventLoopFuture of `Bool` type
     */
    @discardableResult
    func setChatDescription(params: SetChatDescriptionParams) throws -> EventLoopFuture<Bool> {
        let methodURL: URI = .init(string: getMethodURL("setChatDescription"))
        let future: EventLoopFuture<Bool> = tgClient.post(methodURL, params: params, as: nil)
        return future
    }
}
